# Generated by Django 4.0.4 on 2022-04-14 10:37

import cloudinary.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import nickstagram.common_utils.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='NickstagramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=25, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('username', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('[a-z\\_0-9]+', 'The username must contains only lowercase letters, underscores and numbers!'), django.core.validators.MinLengthValidator(4, 'The username must be at least 4 characters long.')])),
                ('first_name', models.CharField(max_length=30, validators=[nickstagram.common_utils.validators.validate_first_name, django.core.validators.MinLengthValidator(2, 'The first name must be at least 2 characters long.')])),
                ('last_name', models.CharField(max_length=30, validators=[nickstagram.common_utils.validators.validate_last_name, django.core.validators.MinLengthValidator(2, 'The first name must be at least 2 characters long.')])),
                ('email', models.EmailField(max_length=60)),
                ('date_of_birth', models.DateField(validators=[nickstagram.common_utils.validators.validate_date_of_birth])),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Do not show', 'Do not show')], default='Do not show', max_length=11, null=True)),
                ('image', cloudinary.models.CloudinaryField(blank=True, default='image/upload/v1649599331/default_gzreya.png', max_length=255, null=True, verbose_name='image')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('friends', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
