# Generated by Django 4.0.3 on 2022-04-06 12:29

from django.db import migrations, models
import nickstagram.accounts.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='images/profile_imgs/default.png', null=True, upload_to='images/profile_imgs', validators=[nickstagram.accounts.validators.file_max_size_validator]),
        ),
    ]
