# Generated by Django 4.0.3 on 2022-04-10 13:32

import cloudinary.models
from django.db import migrations
import nickstagram.common_utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='images/profile_imgs/default.png', max_length=255, null=True, validators=[nickstagram.common_utils.validators.file_max_size_validator], verbose_name='image'),
        ),
    ]
