# Generated by Django 4.0.4 on 2022-04-11 12:02

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='image/upload/v1649599331/default_gzreya.png', max_length=255, null=True, verbose_name='image'),
        ),
    ]
