# Generated by Django 4.0.4 on 2022-04-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='friends',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
