# Generated by Django 4.0.4 on 2022-04-14 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-date_of_creation',)},
        ),
    ]
