# Generated by Django 4.0.3 on 2022-03-18 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import nickstagram.accounts.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_creation', models.DateField(auto_created=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images/uploaded_post_images', validators=[nickstagram.accounts.validators.file_max_size_validator])),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
