# Generated by Django 4.0.3 on 2022-03-23 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_post_date_of_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='hello', max_length=60),
            preserve_default=False,
        ),
    ]
