# Generated by Django 4.0.3 on 2022-04-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_comments_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
