# Generated by Django 4.0.3 on 2022-04-06 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_image'),
        ('web', '0011_alter_likes_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
    ]
