# Generated by Django 4.0.3 on 2022-04-10 13:32

import cloudinary.models
from django.db import migrations
import nickstagram.common_utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, validators=[nickstagram.common_utils.validators.file_max_size_validator], verbose_name='image'),
        ),
    ]
